name: iworkout
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  get_it: ^8.0.2
  dartz: ^0.10.1
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  flutter_bloc: ^8.1.6
  auto_route: ^9.2.2
  flutter_svg: ^2.0.16
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"