// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpibIO3qxd_tzt0eNx96q4oAeUKp5I9o0',
    appId: '1:897188878909:web:3cfc9809784cc798492854',
    messagingSenderId: '897188878909',
    projectId: 'iworkout-e9153',
    authDomain: 'iworkout-e9153.firebaseapp.com',
    storageBucket: 'iworkout-e9153.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCeixJVHFbke6qI1z47k_PnNWYeYjVwRc',
    appId: '1:897188878909:android:18e40483043ccb01492854',
    messagingSenderId: '897188878909',
    projectId: 'iworkout-e9153',
    storageBucket: 'iworkout-e9153.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXx9TVGyTnvu8BHB6gJkSH8ErFr_mk3_Y',
    appId: '1:897188878909:ios:582f2bef6d322e96492854',
    messagingSenderId: '897188878909',
    projectId: 'iworkout-e9153',
    storageBucket: 'iworkout-e9153.firebasestorage.app',
    iosBundleId: 'com.example.iworkout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXx9TVGyTnvu8BHB6gJkSH8ErFr_mk3_Y',
    appId: '1:897188878909:ios:582f2bef6d322e96492854',
    messagingSenderId: '897188878909',
    projectId: 'iworkout-e9153',
    storageBucket: 'iworkout-e9153.firebasestorage.app',
    iosBundleId: 'com.example.iworkout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpibIO3qxd_tzt0eNx96q4oAeUKp5I9o0',
    appId: '1:897188878909:web:f0f687d14f9929e0492854',
    messagingSenderId: '897188878909',
    projectId: 'iworkout-e9153',
    authDomain: 'iworkout-e9153.firebaseapp.com',
    storageBucket: 'iworkout-e9153.firebasestorage.app',
  );
}
